Repository netlify/netlify-headers-parser, pull requests merged in 2021-08, with the labels that each got.

#3 chore: add initial stalebot config
  .github/workflows/stalebot.yml
Labels: type: chore, type: bot

#2 security: add initial secret scan config
  .github/workflows/secretscan.yml
  .github/workflows/trufflehog3-files/suppressions-trufflehog3
Labels: type: security, type: bot

#1 chore: add fossa license scanning
  .github/workflows/fossa.yml
Labels: type: chore, type: bot

#7 fix: headers with no values
  src/normalize.js
  tests/fixtures/netlify_config/values_undefined.toml
  tests/line_parser.js
  tests/netlify_config_parser.js
Labels: type: bug

#6 fix: allow `for` path without a leading slash in `netlify.toml`
  src/normalize.js
  tests/fixtures/netlify_config/for_path_no_slash.toml
  tests/netlify_config_parser.js
Labels: type: bug

#8 feat: remove duplicates
  src/merge.js
  tests/all.js
  tests/fixtures/headers_file/duplicate
  tests/fixtures/headers_file/success_two
  tests/fixtures/netlify_config/duplicate.toml
Labels: type: feature

#9 fix: allow header values to be arrays in `netlify.toml`
  src/normalize.js
  tests/fixtures/netlify_config/invalid_value_array.toml
  tests/fixtures/netlify_config/trim_value_array.toml
  tests/fixtures/netlify_config/value_array.toml
  tests/netlify_config_parser.js
Labels: type: bug

#10 feat!: add lenient parsing
  src/all.js
  src/line_parser.js
  src/merge.js
  src/netlify_config_parser.js
  src/normalize.js
  src/results.js
  tests/all.js
  tests/line_parser.js
  tests/merge.js
  tests/netlify_config_parser.js
Labels: type: feature

#11 feat: add `configHeaders` argument to `parseAllHeaders()`
  src/all.js
  tests/all.js
Labels: type: feature

#12 fix: `mergeHeaders()` should keep valid headers
  src/merge.js
Labels: type: bug

#13 feat!: simplify exported methods
  src/all.js
  src/index.js
  src/merge.js
  tests/all.js
  tests/line_parser.js
  tests/merge.js
  tests/netlify_config_parser.js
Labels: type: feature

#14 chore: simplify tests
  tests/all.js
  tests/helpers/main.js
  tests/line_parser.js
  tests/merge.js
  tests/netlify_config_parser.js
Labels: type: chore

#25 chore: update `renovate.json5`
  renovate.json5
Labels: type: chore

#26 fix: handle `_headers` with wrong file type
  src/line_parser.js
  tests/fixtures/headers_file/invalid_dir/.gitkeep
  tests/line_parser.js
Labels: type: bug

#27 feat!: add `forRegExp` property
  package-lock.json
  package.json
  src/all.js
  src/for_regexp.js
  src/normalize.js
  tests/for_regexp.js
  tests/helpers/main.js
Labels: type: feature

#28 fix: comma-separated lists should append a space
  src/line_parser.js
  src/normalize.js
  tests/line_parser.js
  tests/netlify_config_parser.js
Labels: type: bug

#41 chore(ci): cache npm cache dir between workflow execs
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
Labels: type: chore, automerge
